language: python
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get install -y -q mpich libmpich-dev
  - pip install -r requirements.txt
 command to run tests
script:
  - python -c "import bingo"
