language: python
python:
  - "3.6"
  
before_install:
  - sudo apt-get install -y -q mpich libmpich-dev
  
install:
  - pip install -r requirements.txt
  
script:
  - python -c "import bingo"
  - pytest tests/AGraph
